# DISABLED: New company request template
# This template has been temporarily disabled to prevent overusage of LLM processing.
# Contact the repository owner directly for company submissions.

name: "[DISABLED] New company request"
description: "⚠️ This template is currently disabled. Contact repository owner for submissions."
title: "[DISABLED] New company request"
labels:
  - disabled-template
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Template Disabled
        
        This issue template has been temporarily disabled to prevent overusage of automated processing.
        
        **To submit companies:**
        - Contact the repository owner directly
        - Or wait for this feature to be re-enabled
        
        Thank you for your understanding!

