name: Process new company requests

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  contents: write
  issues: write

jobs:
  process:
    if: contains(join(toJson(github.event.issue.labels.*.name)), 'company-request')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pydantic google-genai>=1.0.0

      - name: Run processor
        id: proc
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          REPO_PATH: ${{ github.workspace }}
        run: |
          python .github/scripts/process_new_companies.py

      - name: Commit changes (if any)
        if: steps.proc.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add wooginawunan.github.io/assets/data/companies.json
          git add wooginawunan.github.io/assets/data/references.json
          git commit -m "chore: add companies from #${{ github.event.issue.number }}"
          git push

      - name: Comment on issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ADDED=${{ steps.proc.outputs.added_names }}
          CHANGED=${{ steps.proc.outputs.changed }}
          ERROR=${{ steps.proc.outputs.error }}
          BODY=$'Update result:\n- changed: '"$CHANGED"$'\n- added: '"${ADDED:-none}"$'\n'"${ERROR:+- error: $ERROR\n}"$''
          curl -s -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d @- <<<'{ "body": '"${BODY@Q}"' }'

      - name: Close issue if processed
        if: steps.proc.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -X PATCH \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d '{"state":"closed"}'

